---
name: Add artifacts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get install -y libpq-dev

      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1

      - name: Build
        run: |
          nim -d:release --opt:speed --parallelBuild:0 --nimcache:.cache c netdata_tsrelay.nim

      - name: Create artifact
        run: zip netdata_tsrelay_linux_x64.zip netdata_tsrelay

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: netdata_tsrelay_linux_x64.zip
          asset_name: netdata_tsrelay_${{ github.ref }}_linux_x64.zip
          tag: ${{ github.ref }}
          overwrite: true
