---
name: Add artifacts

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get install -y libpq-dev

      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1

      - name: Print Nim version
        run: nim -v

      - name: Print dir
        run: ls

      # - name: Build
      #   run: |
      #     nim build -v --opt:size --gc:orc -d:release --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc netdata_tsrelay.nim

      # - name: Get current release
      #   id: current-release
      #   uses: InsonusK/get-latest-release@v1.0.1
      #   with:
      #     myToken: ${{ github.token }}
      #     exclude_types: 'release'
      #     view_top: 1

      # - name: Create artifact
      #   shell: bash
      #   run: zip nimhttpd_${{steps.current-release.outputs.tag_name}}_linux_x64.zip nimhttpd

      # - name: Upload to current release
      #   uses: xresloader/upload-to-github-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     file: 'nimhttpd_v*.zip'
      #     overwrite: true
      #     tag_name: ${{steps.current-release.outputs.tag_name}}
      #     release_id: ${{steps.current-release.outputs.id }}
      #     verbose: true
