---
name: Add artifacts

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get install -y libpq-dev

      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1

      - name: Build
        run: |
          nim -d:release --opt:speed --parallelBuild:0 --nimcache:.cache c netdata_tsrelay.nim

      - name: Create artifact
        shell: bash
        run: zip netdata_tsrelay_${{steps.current-release.outputs.tag_name}}_linux_x64.zip netdata_tsrelay

      - name: Print dir
        run: ls

      - name: Get current release
        id: current-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: 'release'
          view_top: 1

      - name: Upload to current release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'netdata_tsrelay_v*.zip'
          overwrite: true
          tag_name: ${{steps.current-release.outputs.tag_name}}
          release_id: ${{steps.current-release.outputs.id }}
          verbose: true
